CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(20) NOT NULL,
    ward VARCHAR(30) NOT NULL,
    admission_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(500)
);
