INSERT INTO patients (first_name, last_name, age, gender, ward, admission_date, status, reason) VALUES
('Aarav', 'Sharma', 34, 'MALE', 'GENERAL', DATE '2026-04-01', 'ADMITTED', 'Severe flu symptoms'),
('Anaya', 'Patel', 27, 'FEMALE', 'MATERNITY', DATE '2026-04-02', 'ADMITTED', 'Routine maternity observation'),
('Vihaan', 'Singh', 52, 'MALE', 'CARDIOLOGY', DATE '2026-04-03', 'ADMITTED', 'Chest pain monitoring'),
('Ishita', 'Rao', 19, 'FEMALE', 'GENERAL', DATE '2026-04-03', 'ADMITTED', 'High fever and dehydration'),
('Kabir', 'Nair', 41, 'MALE', 'ICU', DATE '2026-04-04', 'ADMITTED', 'Post-operative critical care'),
('Myra', 'Iyer', 63, 'FEMALE', 'ONCOLOGY', DATE '2026-04-04', 'ADMITTED', 'Scheduled chemotherapy cycle'),
('Aditya', 'Mehta', 30, 'MALE', 'GENERAL', DATE '2026-04-05', 'ADMITTED', 'Acute gastritis'),
('Sara', 'Kapoor', 45, 'FEMALE', 'CARDIOLOGY', DATE '2026-04-05', 'ADMITTED', 'Hypertension management'),
('Reyansh', 'Joshi', 12, 'MALE', 'PEDIATRIC', DATE '2026-04-06', 'ADMITTED', 'Respiratory infection'),
('Kiara', 'Verma', 8, 'FEMALE', 'PEDIATRIC', DATE '2026-04-06', 'ADMITTED', 'Viral fever observation'),
('Arjun', 'Bose', 56, 'MALE', 'ICU', DATE '2026-04-07', 'ADMITTED', 'Sepsis management'),
('Siya', 'Mishra', 38, 'FEMALE', 'GENERAL', DATE '2026-04-07', 'ADMITTED', 'Migraine evaluation'),
('Rudra', 'Das', 22, 'MALE', 'GENERAL', DATE '2026-04-08', 'ADMITTED', 'Sports injury recovery'),
('Aanya', 'Kulkarni', 49, 'FEMALE', 'ONCOLOGY', DATE '2026-04-08', 'ADMITTED', 'Oncology follow-up'),
('Dev', 'Pillai', 65, 'MALE', 'CARDIOLOGY', DATE '2026-04-09', 'ADMITTED', 'Arrhythmia observation'),
('Meera', 'Chopra', 31, 'FEMALE', 'MATERNITY', DATE '2026-04-09', 'ADMITTED', 'Third-trimester monitoring'),
('Yash', 'Arora', 40, 'MALE', 'GENERAL', DATE '2026-04-10', 'ADMITTED', 'Diabetic ketoacidosis'),
('Tara', 'Saxena', 28, 'FEMALE', 'GENERAL', DATE '2026-04-10', 'ADMITTED', 'Allergic reaction treatment'),
('Neil', 'Menon', 72, 'MALE', 'ICU', DATE '2026-04-11', 'ADMITTED', 'Stroke observation'),
('Riya', 'Bhatt', 24, 'FEMALE', 'GENERAL', DATE '2026-04-11', 'ADMITTED', 'Appendicitis pre-op'),
('Parth', 'Jain', 36, 'MALE', 'CARDIOLOGY', DATE '2026-04-12', 'ADMITTED', 'Cardiac stress test prep'),
('Navya', 'Ghosh', 43, 'FEMALE', 'ONCOLOGY', DATE '2026-04-12', 'ADMITTED', 'Radiotherapy session'),
('Laksh', 'Agarwal', 17, 'MALE', 'PEDIATRIC', DATE '2026-04-13', 'ADMITTED', 'Asthma exacerbation'),
('Diya', 'Pandey', 10, 'FEMALE', 'PEDIATRIC', DATE '2026-04-13', 'ADMITTED', 'Tonsillitis care'),
('Kunal', 'Bhatia', 58, 'MALE', 'GENERAL', DATE '2026-04-14', 'ADMITTED', 'Kidney stone pain management'),
('Naina', 'Dutta', 33, 'FEMALE', 'GENERAL', DATE '2026-04-14', 'ADMITTED', 'Severe anemia treatment'),
('Ayaan', 'Roy', 47, 'MALE', 'ICU', DATE '2026-04-15', 'ADMITTED', 'Ventilator support'),
('Pihu', 'Malhotra', 29, 'FEMALE', 'MATERNITY', DATE '2026-04-15', 'ADMITTED', 'Labor induction'),
('Om', 'Tiwari', 55, 'MALE', 'CARDIOLOGY', DATE '2026-04-15', 'ADMITTED', 'Post-angioplasty care'),
('Ira', 'Yadav', 39, 'FEMALE', 'GENERAL', DATE '2026-04-15', 'ADMITTED', 'Acute pancreatitis observation'),
('Rohan', 'Bansal', 32, 'MALE', 'GENERAL', DATE '2026-03-25', 'DISCHARGED', 'Recovered from dengue'),
('Mahi', 'Gupta', 26, 'FEMALE', 'GENERAL', DATE '2026-03-20', 'DISCHARGED', 'Food poisoning treated'),
('Samar', 'Khanna', 61, 'MALE', 'CARDIOLOGY', DATE '2026-03-18', 'DISCHARGED', 'Stable after cardiac monitoring'),
('Vanya', 'Shukla', 14, 'FEMALE', 'PEDIATRIC', DATE '2026-03-21', 'DISCHARGED', 'Recovered from pneumonia'),
('Hrithik', 'Sethi', 44, 'MALE', 'ONCOLOGY', DATE '2026-03-19', 'DISCHARGED', 'Completed treatment cycle'),
('Aditi', 'Madan', 35, 'FEMALE', 'MATERNITY', DATE '2026-03-22', 'DISCHARGED', 'Post-delivery discharge'),
('Manav', 'Puri', 53, 'MALE', 'GENERAL', DATE '2026-03-23', 'DISCHARGED', 'Controlled blood sugar'),
('Kavya', 'Lal', 46, 'FEMALE', 'GENERAL', DATE '2026-03-24', 'DISCHARGED', 'Recovered from infection'),
('Pranav', 'Suri', 67, 'MALE', 'ICU', DATE '2026-03-17', 'DISCHARGED', 'Condition stabilized'),
('Tanvi', 'Ahuja', 21, 'FEMALE', 'GENERAL', DATE '2026-03-26', 'DISCHARGED', 'Minor surgery recovery');
