CREATE TABLE doctor_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name VARCHAR(255) NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    shift_start TIME NOT NULL,
    shift_end TIME NOT NULL,
    department VARCHAR(100) NOT NULL,
    room_number VARCHAR(30)
);
